version: "3.9"
services:
  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus:/etc/prometheus/
    ports:
      - 9090:9090
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    environment:
      - TZ=Europe/Moscow
    networks:
      - default
  grafana:
    image: grafana/grafana:8.3.3
    container_name: grafana
    volumes:
      - ./grafana/grafana-data:/var/lib/grafana
    ports:
      - 3000:3000
    networks:
      - default
