version: "3.9"
services:
  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus:/etc/prometheus/
    ports:
      - 9090:9090
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    environment:
      - TZ=Europe/Moscow
    networks:
      - default
  grafana:
    image: grafana/grafana:8.3.3
    container_name: grafana
    volumes:
      - ./grafana/grafana-data:/var/lib/grafana
    ports:
      - 3000:3000
    networks:
      - default
  zookeeper:
    image: wurstmeister/zookeeper
    platform: linux/amd64
    container_name: zookeeper
    hostname: zookeeper
    ports:
      - "2181:2181"
    networks:
      - default
    restart: unless-stopped
  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    networks:
      - default
    ports:
      - 9092:9092
      - 9094:9094
    environment:
      KAFKA_LISTENERS: INTERNAL://0.0.0.0:9094,EXTERNAL://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9094,EXTERNAL://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
