global:
  scrape_interval: 30s
  scrape_timeout: 10s

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 10s
    static_configs:
      - targets:
          - host.docker.internal:9091
          - host.docker.internal:44003
          - host.docker.internal:44000
